---

- hosts: all
    
  vars:
     VERSION: 9.1
     project_path: /home/yherar/sre-bootcamp-yherar-11-11-2019/Code
     snapshot: False
    

  tasks:
    - name: Creacion de version release
      command: "mvn -f {{ project_path }}/pom.xml versions:set -DnewVersion={{ VERSION }}"
      when: not snapshot 
      
    - name: Deploy a nexus
      command: "mvn -f {{ project_path }}/pom.xml clean deploy"

...
 
