---

- hosts: all
    
  vars:
    project_path: /home/yherar/sre-bootcamp-yherar-11-11-2019/Code
    

  tasks:
    - name: Creacion de version release
      command: "mvn -f {{ project_path }}/pom.xml versions:set -DnewVersion={{ 9.1 }}"
      
      
    - name: Deploy a nexus
      command: "mvn -f {{ project_path }}/pom.xml clean deploy"
...
 
